name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: setup chromedriver    
    - uses: actions/setup-java@v1
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '77.0.3865.40'
    - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          
    - name: copy file
      uses: actions/setup-java@v1
      with:
        source: "/home/runner/work/setup-chromedriver/setup-chromedriver"
        target: "/home/runner/work/exame-automacao-testes-front/exame-automacao-testes-front/src/main/resources/"
    
    - name: Build with Maven
      run: mvn test
